### ISSUE TITLE
ngrx-selector-for-select doesn't work properly

### ISSUE THREAD

**Issue by martinmicunda** [timdeschryver/ngrx-tslint-rules#2]
Hi,

It seems like `ngrx-selector-for-select` doesn't work properly as it throwing lint error on rxjs `map` function.

![screen_1](https://user-images.githubusercontent.com/1643606/63581283-9e195900-c58e-11e9-9514-41c12300ae5c.png)
![screen_2](https://user-images.githubusercontent.com/1643606/63581295-a1144980-c58e-11e9-8483-d54c5aae5878.png)

**Comment by timdeschryver** [comment]
You're right, thanks for creating the issue!
