### ISSUE TITLE
Using string or props drilling is not preferred

### ISSUE THREAD

**Issue by biesbjerg** [timdeschryver/ngrx-tslint-rules#4]
I think there might be a bug while detecting if strings/props are used when selecting from state (probably because I group my selectors in an object?)

Error:
`ERROR: /Users/kim/apps/mindly/src/app/settings/effects/settings.effects.ts:23:16 - Using string or props drilling is not preferred, use a selector instead`

Code
```ts
import { SettingsSelectors } from '@app/settings/selectors';

@Injectable()
export class SettingsEffects {
	public showOnboardingPage$ = createEffect(
		() =>
			this.actions$.pipe(
				ofType(StoreSyncActions.restoreStateSuccess, StoreSyncActions.restoreStateFailure),
				exhaustMap(() => this.store$.pipe(select(SettingsSelectors.showOnboardingPage))), // Line 23
				tap(show => {
					if (show) {
						this.navController.navigateRoot(['onboarding']);
					}
				})
			),
		{ dispatch: false }
	);
}
```

**Comment by timdeschryver** [comment]
Thanks for bringing this up, I will take a look at it!
Or if you'd like you can too 🙂

**Comment by timdeschryver** [comment]
The problem is that it's used within a rxjs operator.

**Comment by biesbjerg** [comment]
Thanks Tim! 😊

**Comment by timdeschryver** [comment]
You're welcome 🙂
