### ISSUE TITLE
[Feat]: Add lint rule for using switchMap within Effects

### ISSUE THREAD

**Issue by brandonroberts** [timdeschryver/ngrx-tslint-rules#40]
There's a small chance you would actually use switchMap in an Effect, so it would nice to warn the majority people to use something else, like concatMap

**Comment by timdeschryver** [comment]
We're exporting some of the rules from [rxjs-tslint-rules](https://github.com/cartant/rxjs-tslint-rules), one of them is [rxjs-no-unsafe-switchmap](https://github.com/cartant/rxjs-tslint-rules#rxjs-no-unsafe-switchmap) (and can be configured). Would this fit your needs? If not, we can look into creating our own rule for it.

**Comment by brandonroberts** [comment]
Yep, I think that one would work even though it's a separate thing to install

**Comment by timdeschryver** [comment]
Hmmm, you shouldn't have to install it.
It should be included in ngrx-tslint-rules, in the recommended config, or you can enable it [manually](https://github.com/timdeschryver/ngrx-tslint-rules/blob/master/src/recommended.ts#L43).

**Comment by brandonroberts** [comment]
Ahh, I see. Ok cool. Thanks!
