### ISSUE TITLE
Angular 10 peer dependencies

### ISSUE THREAD

**Issue by robinpellegrims** [timdeschryver/ngrx-tslint-rules#45]
First of all, thanks a lot @timdeschryver for this library as it proved to be very helpful for keeping consistency between many applications (and devs) using ngrx in a monorepo.

After updating to Angular 10 (which also updates tslint to v6), the following warning is shown for ngrx-tslint-rules:
`warning " > ngrx-tslint-rules@2.1.3" has incorrect peer dependency "tslint@^5.0.0".`

Would it be possible to bump the version of the tslint peer dependency to v6?

**Comment by timdeschryver** [comment]
Oh sure, that should be possible.
Do you want to create a Pull Request for this @robinpellegrims ?
