### ISSUE TITLE
ngrx-no-typed-store - How to deal with nested selectors? 

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/ngrx-tslint-rules#48]
I have a Facade, like this:

```ts
@Injectable()
export class CheckoutFacade {
  readonly failStatus$ = this.store$.select(selectFailStatus$);

  constructor(private readonly store$: Store<any>) {} // intentionally typed as `any`
}
```

and `selectFailStatus`, declared as selector, is like this:

```ts
export const getCheckoutState = createFeatureSelector<
  CheckoutPartialState,
  State
>(CHECKOUT_FEATURE_KEY);

export const selectFailStatus = createSelector(
  getCheckoutState,
  ({ failStatus }) => failStatus,
);
```

and for completenesses, here's the `State`:

```ts

export interface State {
  readonly failStatus: boolean;
  // other properties
}

export interface CheckoutPartialState {
  readonly [CHECKOUT_FEATURE_KEY]: State;
}
```

When I enable the rule `ngrx-no-typed-store`, it tells me that `Store` shouldn't be typed, however if I don't type it as `any`, for example, I got type errors like this:

![Captura de Tela 2020-11-20 às 17 59 28](https://user-images.githubusercontent.com/11965907/99849396-4505ef80-2b5a-11eb-961c-770123a7b1f8.png)

<hr>

So, my question is: how this rule works for nested selectors like this? Am I doing something wrong? Thanks in advance :)

**Comment by timdeschryver** [comment]
I suppose you have strictly mode on?
If so, we're tracking that in the ngrx repo at https://github.com/ngrx/platform/issues/2780

**Comment by rafaelss95** [comment]
> I suppose you have strictly mode on?

Yes.

> If so, we're tracking that in the ngrx repo at [ngrx/platform#2780](https://github.com/ngrx/platform/issues/2780)

In this case I'm gonna close this, thanks!
