### ISSUE TITLE
Remove ngrx-unique-reducers-action rule

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/ngrx-tslint-rules#9]
With  https://github.com/ngrx/platform/pull/2103 merged in NgRx, we don't need the rule `ngrx-unique-reducers-action` anymore.
So we can remove the rule, the spec for this rule, and the documentation.

- https://github.com/timdeschryver/ngrx-tslint-rules/blob/master/src/rules/ngrxUniqueReducerActionsRule.ts
- https://github.com/timdeschryver/ngrx-tslint-rules/tree/master/test/rules/unique-reducer-actions
- https://github.com/timdeschryver/ngrx-tslint-rules/blob/master/src/recommended.ts#L8
- https://github.com/timdeschryver/ngrx-tslint-rules/blob/master/README.md

**Comment by danny95djb** [comment]
I'm up for giving this a go.

**Comment by timdeschryver** [comment]
Awesome! 🎉
